apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pd
  name: test-pd
  namespace: test
spec:
  containers:
    - image: nginx
      name: test-pd
  dnsPolicy: ClusterFirst
  restartPolicy: Always